# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(352, 468)
        Calculator.setMinimumSize(QtCore.QSize(352, 468))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/OkayChamp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calculator.setWindowIcon(icon)
        Calculator.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(54, 57, 62);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton\n"
"{\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton.lightbutton\n"
"{\n"
"    background-color: rgb(47, 49, 54);    \n"
"}\n"
"\n"
"QPushButton.darkbutton\n"
"{\n"
"    \n"
"    background-color: rgb(32, 34, 37);\n"
"}\n"
"\n"
"QPushButton.resultbutton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 89, 99);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(115, 138, 219);\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    \n"
"    background-color: rgb(94, 114, 179);\n"
"}\n"
"\n"
"QPushButton.hamburger::hover\n"
"{\n"
"    background-color: rgb(54, 57, 62);\n"
"    color: rgb(115, 138, 219);\n"
"}\n"
"\n"
"QPushButton.hamburger::pressed\n"
"{\n"
"    \n"
"    color: rgb(94, 114, 179);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_result = QtWidgets.QLineEdit(self.centralwidget)
        self.line_result.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.line_result.setFont(font)
        self.line_result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_result.setFrame(False)
        self.line_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_result.setReadOnly(True)
        self.line_result.setObjectName("line_result")
        self.gridLayout_2.addWidget(self.line_result, 2, 0, 1, 2)
        self.button_change = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_change.sizePolicy().hasHeightForWidth())
        self.button_change.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_change.setFont(font)
        self.button_change.setObjectName("button_change")
        self.gridLayout_2.addWidget(self.button_change, 0, 0, 1, 1)
        self.line_subresult = QtWidgets.QLineEdit(self.centralwidget)
        self.line_subresult.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_subresult.setFont(font)
        self.line_subresult.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_subresult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_subresult.setStyleSheet("color: rgb(189, 189, 189);")
        self.line_subresult.setText("")
        self.line_subresult.setFrame(False)
        self.line_subresult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_subresult.setReadOnly(True)
        self.line_subresult.setObjectName("line_subresult")
        self.gridLayout_2.addWidget(self.line_subresult, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_del = QtWidgets.QPushButton(self.centralwidget)
        self.button_del.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_del.sizePolicy().hasHeightForWidth())
        self.button_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_del.setFont(font)
        self.button_del.setObjectName("button_del")
        self.gridLayout.addWidget(self.button_del, 1, 4, 1, 1)
        self.button_zero = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_zero.sizePolicy().hasHeightForWidth())
        self.button_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_zero.setFont(font)
        self.button_zero.setObjectName("button_zero")
        self.gridLayout.addWidget(self.button_zero, 6, 2, 1, 1)
        self.buttoni = QtWidgets.QPushButton(self.centralwidget)
        self.buttoni.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttoni.sizePolicy().hasHeightForWidth())
        self.buttoni.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttoni.setFont(font)
        self.buttoni.setObjectName("buttoni")
        self.gridLayout.addWidget(self.buttoni, 0, 2, 1, 1)
        self.buttonh = QtWidgets.QPushButton(self.centralwidget)
        self.buttonh.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonh.sizePolicy().hasHeightForWidth())
        self.buttonh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonh.setFont(font)
        self.buttonh.setObjectName("buttonh")
        self.gridLayout.addWidget(self.buttonh, 0, 1, 1, 1)
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minus.sizePolicy().hasHeightForWidth())
        self.button_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        self.gridLayout.addWidget(self.button_minus, 4, 4, 1, 1)
        self.button_negation = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_negation.sizePolicy().hasHeightForWidth())
        self.button_negation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_negation.setFont(font)
        self.button_negation.setObjectName("button_negation")
        self.gridLayout.addWidget(self.button_negation, 6, 1, 1, 1)
        self.button_pow = QtWidgets.QPushButton(self.centralwidget)
        self.button_pow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pow.sizePolicy().hasHeightForWidth())
        self.button_pow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_pow.setFont(font)
        self.button_pow.setObjectName("button_pow")
        self.gridLayout.addWidget(self.button_pow, 2, 2, 1, 1)
        self.button_four = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_four.sizePolicy().hasHeightForWidth())
        self.button_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_four.setFont(font)
        self.button_four.setObjectName("button_four")
        self.gridLayout.addWidget(self.button_four, 4, 1, 1, 1)
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_plus.sizePolicy().hasHeightForWidth())
        self.button_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_plus.setFont(font)
        self.button_plus.setObjectName("button_plus")
        self.gridLayout.addWidget(self.button_plus, 5, 4, 1, 1)
        self.button_three = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_three.sizePolicy().hasHeightForWidth())
        self.button_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_three.setFont(font)
        self.button_three.setObjectName("button_three")
        self.gridLayout.addWidget(self.button_three, 3, 3, 1, 1)
        self.button_nine = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_nine.sizePolicy().hasHeightForWidth())
        self.button_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_nine.setFont(font)
        self.button_nine.setObjectName("button_nine")
        self.gridLayout.addWidget(self.button_nine, 5, 3, 1, 1)
        self.button_decimal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_decimal.sizePolicy().hasHeightForWidth())
        self.button_decimal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_decimal.setFont(font)
        self.button_decimal.setObjectName("button_decimal")
        self.gridLayout.addWidget(self.button_decimal, 6, 3, 1, 1)
        self.button_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.button_multiply.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_multiply.sizePolicy().hasHeightForWidth())
        self.button_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_multiply.setFont(font)
        self.button_multiply.setObjectName("button_multiply")
        self.gridLayout.addWidget(self.button_multiply, 3, 4, 1, 1)
        self.button_eight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_eight.sizePolicy().hasHeightForWidth())
        self.button_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_eight.setFont(font)
        self.button_eight.setObjectName("button_eight")
        self.gridLayout.addWidget(self.button_eight, 5, 2, 1, 1)
        self.button_c = QtWidgets.QPushButton(self.centralwidget)
        self.button_c.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_c.sizePolicy().hasHeightForWidth())
        self.button_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_c.setFont(font)
        self.button_c.setObjectName("button_c")
        self.gridLayout.addWidget(self.button_c, 1, 3, 1, 1)
        self.buttonj = QtWidgets.QPushButton(self.centralwidget)
        self.buttonj.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonj.sizePolicy().hasHeightForWidth())
        self.buttonj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonj.setFont(font)
        self.buttonj.setObjectName("buttonj")
        self.gridLayout.addWidget(self.buttonj, 0, 3, 1, 1)
        self.button_five = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_five.sizePolicy().hasHeightForWidth())
        self.button_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_five.setFont(font)
        self.button_five.setObjectName("button_five")
        self.gridLayout.addWidget(self.button_five, 4, 2, 1, 1)
        self.button_seven = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_seven.sizePolicy().hasHeightForWidth())
        self.button_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_seven.setFont(font)
        self.button_seven.setObjectName("button_seven")
        self.gridLayout.addWidget(self.button_seven, 5, 1, 1, 1)
        self.button_two = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_two.sizePolicy().hasHeightForWidth())
        self.button_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_two.setFont(font)
        self.button_two.setObjectName("button_two")
        self.gridLayout.addWidget(self.button_two, 3, 2, 1, 1)
        self.button_slashx = QtWidgets.QPushButton(self.centralwidget)
        self.button_slashx.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_slashx.sizePolicy().hasHeightForWidth())
        self.button_slashx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_slashx.setFont(font)
        self.button_slashx.setObjectName("button_slashx")
        self.gridLayout.addWidget(self.button_slashx, 2, 1, 1, 1)
        self.button_percent = QtWidgets.QPushButton(self.centralwidget)
        self.button_percent.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_percent.sizePolicy().hasHeightForWidth())
        self.button_percent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_percent.setFont(font)
        self.button_percent.setObjectName("button_percent")
        self.gridLayout.addWidget(self.button_percent, 1, 1, 1, 1)
        self.button_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.button_sqrt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sqrt.sizePolicy().hasHeightForWidth())
        self.button_sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setObjectName("button_sqrt")
        self.gridLayout.addWidget(self.button_sqrt, 2, 3, 1, 1)
        self.button_six = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_six.sizePolicy().hasHeightForWidth())
        self.button_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_six.setFont(font)
        self.button_six.setObjectName("button_six")
        self.gridLayout.addWidget(self.button_six, 4, 3, 1, 1)
        self.button_divide = QtWidgets.QPushButton(self.centralwidget)
        self.button_divide.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_divide.sizePolicy().hasHeightForWidth())
        self.button_divide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_divide.setFont(font)
        self.button_divide.setObjectName("button_divide")
        self.gridLayout.addWidget(self.button_divide, 2, 4, 1, 1)
        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        self.button_equals.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_equals.sizePolicy().hasHeightForWidth())
        self.button_equals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_equals.setFont(font)
        self.button_equals.setObjectName("button_equals")
        self.gridLayout.addWidget(self.button_equals, 6, 4, 1, 1)
        self.button_one = QtWidgets.QPushButton(self.centralwidget)
        self.button_one.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_one.sizePolicy().hasHeightForWidth())
        self.button_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_one.setFont(font)
        self.button_one.setObjectName("button_one")
        self.gridLayout.addWidget(self.button_one, 3, 1, 1, 1)
        self.buttonk = QtWidgets.QPushButton(self.centralwidget)
        self.buttonk.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonk.sizePolicy().hasHeightForWidth())
        self.buttonk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonk.setFont(font)
        self.buttonk.setObjectName("buttonk")
        self.gridLayout.addWidget(self.buttonk, 0, 4, 1, 1)
        self.button_ce = QtWidgets.QPushButton(self.centralwidget)
        self.button_ce.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ce.sizePolicy().hasHeightForWidth())
        self.button_ce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ce.setFont(font)
        self.button_ce.setObjectName("button_ce")
        self.gridLayout.addWidget(self.button_ce, 1, 2, 1, 1)
        self.buttong = QtWidgets.QPushButton(self.centralwidget)
        self.buttong.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttong.sizePolicy().hasHeightForWidth())
        self.buttong.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttong.setFont(font)
        self.buttong.setDefault(False)
        self.buttong.setFlat(False)
        self.buttong.setObjectName("buttong")
        self.gridLayout.addWidget(self.buttong, 0, 0, 1, 1)
        self.buttonf = QtWidgets.QPushButton(self.centralwidget)
        self.buttonf.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonf.sizePolicy().hasHeightForWidth())
        self.buttonf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonf.setFont(font)
        self.buttonf.setObjectName("buttonf")
        self.gridLayout.addWidget(self.buttonf, 1, 0, 1, 1)
        self.buttone = QtWidgets.QPushButton(self.centralwidget)
        self.buttone.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttone.sizePolicy().hasHeightForWidth())
        self.buttone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttone.setFont(font)
        self.buttone.setObjectName("buttone")
        self.gridLayout.addWidget(self.buttone, 2, 0, 1, 1)
        self.buttond = QtWidgets.QPushButton(self.centralwidget)
        self.buttond.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttond.sizePolicy().hasHeightForWidth())
        self.buttond.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttond.setFont(font)
        self.buttond.setObjectName("buttond")
        self.gridLayout.addWidget(self.buttond, 3, 0, 1, 1)
        self.buttonc = QtWidgets.QPushButton(self.centralwidget)
        self.buttonc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonc.sizePolicy().hasHeightForWidth())
        self.buttonc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonc.setFont(font)
        self.buttonc.setObjectName("buttonc")
        self.gridLayout.addWidget(self.buttonc, 4, 0, 1, 1)
        self.buttonb = QtWidgets.QPushButton(self.centralwidget)
        self.buttonb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonb.sizePolicy().hasHeightForWidth())
        self.buttonb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonb.setFont(font)
        self.buttonb.setObjectName("buttonb")
        self.gridLayout.addWidget(self.buttonb, 5, 0, 1, 1)
        self.buttona = QtWidgets.QPushButton(self.centralwidget)
        self.buttona.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttona.sizePolicy().hasHeightForWidth())
        self.buttona.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttona.setFont(font)
        self.buttona.setObjectName("buttona")
        self.gridLayout.addWidget(self.buttona, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 2)
        self.label_style = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_style.setFont(font)
        self.label_style.setObjectName("label_style")
        self.gridLayout_2.addWidget(self.label_style, 0, 1, 1, 1)
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)
        Calculator.setTabOrder(self.button_one, self.button_two)
        Calculator.setTabOrder(self.button_two, self.button_three)
        Calculator.setTabOrder(self.button_three, self.button_four)
        Calculator.setTabOrder(self.button_four, self.button_five)
        Calculator.setTabOrder(self.button_five, self.button_six)
        Calculator.setTabOrder(self.button_six, self.button_seven)
        Calculator.setTabOrder(self.button_seven, self.button_eight)
        Calculator.setTabOrder(self.button_eight, self.button_nine)
        Calculator.setTabOrder(self.button_nine, self.button_negation)
        Calculator.setTabOrder(self.button_negation, self.button_zero)
        Calculator.setTabOrder(self.button_zero, self.button_decimal)
        Calculator.setTabOrder(self.button_decimal, self.button_percent)
        Calculator.setTabOrder(self.button_percent, self.button_ce)
        Calculator.setTabOrder(self.button_ce, self.button_c)
        Calculator.setTabOrder(self.button_c, self.button_del)
        Calculator.setTabOrder(self.button_del, self.button_slashx)
        Calculator.setTabOrder(self.button_slashx, self.button_pow)
        Calculator.setTabOrder(self.button_pow, self.button_sqrt)
        Calculator.setTabOrder(self.button_sqrt, self.button_divide)
        Calculator.setTabOrder(self.button_divide, self.button_multiply)
        Calculator.setTabOrder(self.button_multiply, self.button_minus)
        Calculator.setTabOrder(self.button_minus, self.button_plus)
        Calculator.setTabOrder(self.button_plus, self.button_equals)
        Calculator.setTabOrder(self.button_equals, self.button_change)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "CalcChamp"))
        Calculator.setProperty("class", _translate("Calculator", "darkButton"))
        self.line_result.setText(_translate("Calculator", "0"))
        self.button_change.setText(_translate("Calculator", "☰"))
        self.button_change.setProperty("class", _translate("Calculator", "hamburger"))
        self.button_del.setText(_translate("Calculator", "DEL"))
        self.button_del.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_zero.setText(_translate("Calculator", "0"))
        self.button_zero.setProperty("class", _translate("Calculator", "lightbutton"))
        self.buttoni.setText(_translate("Calculator", "..."))
        self.buttoni.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttonh.setText(_translate("Calculator", "..."))
        self.buttonh.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_minus.setText(_translate("Calculator", "-"))
        self.button_minus.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_negation.setText(_translate("Calculator", "+-"))
        self.button_negation.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_pow.setText(_translate("Calculator", "x^2"))
        self.button_pow.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_four.setText(_translate("Calculator", "4"))
        self.button_four.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_plus.setText(_translate("Calculator", "+"))
        self.button_plus.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_three.setText(_translate("Calculator", "3"))
        self.button_three.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_nine.setText(_translate("Calculator", "9"))
        self.button_nine.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_decimal.setText(_translate("Calculator", ","))
        self.button_decimal.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_multiply.setText(_translate("Calculator", "*"))
        self.button_multiply.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_eight.setText(_translate("Calculator", "8"))
        self.button_eight.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_c.setText(_translate("Calculator", "C"))
        self.button_c.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttonj.setText(_translate("Calculator", "..."))
        self.buttonj.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_five.setText(_translate("Calculator", "5"))
        self.button_five.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_seven.setText(_translate("Calculator", "7"))
        self.button_seven.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_two.setText(_translate("Calculator", "2"))
        self.button_two.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_slashx.setText(_translate("Calculator", "1/x"))
        self.button_slashx.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_percent.setText(_translate("Calculator", "%"))
        self.button_percent.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_sqrt.setText(_translate("Calculator", "√x"))
        self.button_sqrt.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_six.setText(_translate("Calculator", "6"))
        self.button_six.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_divide.setText(_translate("Calculator", "/"))
        self.button_divide.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_equals.setText(_translate("Calculator", "="))
        self.button_equals.setProperty("class", _translate("Calculator", "resultbutton"))
        self.button_one.setText(_translate("Calculator", "1"))
        self.button_one.setProperty("class", _translate("Calculator", "lightbutton"))
        self.buttonk.setText(_translate("Calculator", "..."))
        self.buttonk.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_ce.setText(_translate("Calculator", "CE"))
        self.button_ce.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttong.setText(_translate("Calculator", "..."))
        self.buttong.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttonf.setText(_translate("Calculator", "..."))
        self.buttonf.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttone.setText(_translate("Calculator", "..."))
        self.buttone.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttond.setText(_translate("Calculator", "..."))
        self.buttond.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttonc.setText(_translate("Calculator", "..."))
        self.buttonc.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttonb.setText(_translate("Calculator", "..."))
        self.buttonb.setProperty("class", _translate("Calculator", "darkbutton"))
        self.buttona.setText(_translate("Calculator", "..."))
        self.buttona.setProperty("class", _translate("Calculator", "darkbutton"))
        self.label_style.setText(_translate("Calculator", "Scientific"))

