# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(352, 468)
        Calculator.setMinimumSize(QtCore.QSize(352, 468))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/OkayChamp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calculator.setWindowIcon(icon)
        Calculator.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(54, 57, 62);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton\n"
"{\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton.lightbutton\n"
"{\n"
"    background-color: rgb(47, 49, 54);    \n"
"}\n"
"\n"
"QPushButton.darkbutton\n"
"{\n"
"    \n"
"    background-color: rgb(32, 34, 37);\n"
"}\n"
"\n"
"QPushButton.resultbutton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 89, 99);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(115, 138, 219);\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    \n"
"    background-color: rgb(94, 114, 179);\n"
"}\n"
"\n"
"QPushButton.hamburger::hover\n"
"{\n"
"    background-color: rgb(54, 57, 62);\n"
"    color: rgb(115, 138, 219);\n"
"}\n"
"\n"
"QPushButton.hamburger::pressed\n"
"{\n"
"    \n"
"    color: rgb(94, 114, 179);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_change = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_change.sizePolicy().hasHeightForWidth())
        self.button_change.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_change.setFont(font)
        self.button_change.setObjectName("button_change")
        self.gridLayout_2.addWidget(self.button_change, 0, 0, 1, 1)
        self.line_subresult = QtWidgets.QLineEdit(self.centralwidget)
        self.line_subresult.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_subresult.setFont(font)
        self.line_subresult.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_subresult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_subresult.setStyleSheet("color: rgb(189, 189, 189);")
        self.line_subresult.setText("")
        self.line_subresult.setFrame(False)
        self.line_subresult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_subresult.setReadOnly(True)
        self.line_subresult.setObjectName("line_subresult")
        self.gridLayout_2.addWidget(self.line_subresult, 2, 0, 1, 2)
        self.label_style = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_style.setFont(font)
        self.label_style.setObjectName("label_style")
        self.gridLayout_2.addWidget(self.label_style, 0, 1, 1, 1)
        self.line_result = QtWidgets.QLineEdit(self.centralwidget)
        self.line_result.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.line_result.setFont(font)
        self.line_result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_result.setFrame(False)
        self.line_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_result.setReadOnly(True)
        self.line_result.setObjectName("line_result")
        self.gridLayout_2.addWidget(self.line_result, 3, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        self.button_equals.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_equals.sizePolicy().hasHeightForWidth())
        self.button_equals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_equals.setFont(font)
        self.button_equals.setObjectName("button_equals")
        self.gridLayout.addWidget(self.button_equals, 9, 5, 1, 1)
        self.button_five = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_five.sizePolicy().hasHeightForWidth())
        self.button_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_five.setFont(font)
        self.button_five.setObjectName("button_five")
        self.gridLayout.addWidget(self.button_five, 7, 3, 1, 1)
        self.button_eight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_eight.sizePolicy().hasHeightForWidth())
        self.button_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_eight.setFont(font)
        self.button_eight.setObjectName("button_eight")
        self.gridLayout.addWidget(self.button_eight, 8, 3, 1, 1)
        self.button_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.button_multiply.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_multiply.sizePolicy().hasHeightForWidth())
        self.button_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_multiply.setFont(font)
        self.button_multiply.setObjectName("button_multiply")
        self.gridLayout.addWidget(self.button_multiply, 6, 5, 1, 1)
        self.button_two = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_two.sizePolicy().hasHeightForWidth())
        self.button_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_two.setFont(font)
        self.button_two.setObjectName("button_two")
        self.gridLayout.addWidget(self.button_two, 6, 3, 1, 1)
        self.button_root = QtWidgets.QPushButton(self.centralwidget)
        self.button_root.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_root.sizePolicy().hasHeightForWidth())
        self.button_root.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_root.setFont(font)
        self.button_root.setObjectName("button_root")
        self.gridLayout.addWidget(self.button_root, 4, 3, 1, 1)
        self.button_decimal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_decimal.sizePolicy().hasHeightForWidth())
        self.button_decimal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_decimal.setFont(font)
        self.button_decimal.setObjectName("button_decimal")
        self.gridLayout.addWidget(self.button_decimal, 9, 4, 1, 1)
        self.button_c = QtWidgets.QPushButton(self.centralwidget)
        self.button_c.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_c.sizePolicy().hasHeightForWidth())
        self.button_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_c.setFont(font)
        self.button_c.setObjectName("button_c")
        self.gridLayout.addWidget(self.button_c, 2, 4, 1, 1)
        self.button_ce = QtWidgets.QPushButton(self.centralwidget)
        self.button_ce.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ce.sizePolicy().hasHeightForWidth())
        self.button_ce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ce.setFont(font)
        self.button_ce.setObjectName("button_ce")
        self.gridLayout.addWidget(self.button_ce, 2, 3, 1, 1)
        self.button_nine = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_nine.sizePolicy().hasHeightForWidth())
        self.button_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_nine.setFont(font)
        self.button_nine.setObjectName("button_nine")
        self.gridLayout.addWidget(self.button_nine, 8, 4, 1, 1)
        self.button_three = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_three.sizePolicy().hasHeightForWidth())
        self.button_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_three.setFont(font)
        self.button_three.setObjectName("button_three")
        self.gridLayout.addWidget(self.button_three, 6, 4, 1, 1)
        self.button_sqr = QtWidgets.QPushButton(self.centralwidget)
        self.button_sqr.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sqr.sizePolicy().hasHeightForWidth())
        self.button_sqr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_sqr.setFont(font)
        self.button_sqr.setObjectName("button_sqr")
        self.gridLayout.addWidget(self.button_sqr, 5, 4, 1, 1)
        self.button_six = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_six.sizePolicy().hasHeightForWidth())
        self.button_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_six.setFont(font)
        self.button_six.setObjectName("button_six")
        self.gridLayout.addWidget(self.button_six, 7, 4, 1, 1)
        self.button_negation = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_negation.sizePolicy().hasHeightForWidth())
        self.button_negation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_negation.setFont(font)
        self.button_negation.setObjectName("button_negation")
        self.gridLayout.addWidget(self.button_negation, 2, 2, 1, 1)
        self.button_one = QtWidgets.QPushButton(self.centralwidget)
        self.button_one.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_one.sizePolicy().hasHeightForWidth())
        self.button_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_one.setFont(font)
        self.button_one.setObjectName("button_one")
        self.gridLayout.addWidget(self.button_one, 6, 2, 1, 1)
        self.button_exp = QtWidgets.QPushButton(self.centralwidget)
        self.button_exp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_exp.sizePolicy().hasHeightForWidth())
        self.button_exp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_exp.setFont(font)
        self.button_exp.setObjectName("button_exp")
        self.gridLayout.addWidget(self.button_exp, 4, 5, 1, 1)
        self.button_four = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_four.sizePolicy().hasHeightForWidth())
        self.button_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_four.setFont(font)
        self.button_four.setObjectName("button_four")
        self.gridLayout.addWidget(self.button_four, 7, 2, 1, 1)
        self.button_seven = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_seven.sizePolicy().hasHeightForWidth())
        self.button_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_seven.setFont(font)
        self.button_seven.setObjectName("button_seven")
        self.gridLayout.addWidget(self.button_seven, 8, 2, 1, 1)
        self.button_divide_by_x = QtWidgets.QPushButton(self.centralwidget)
        self.button_divide_by_x.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_divide_by_x.sizePolicy().hasHeightForWidth())
        self.button_divide_by_x.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_divide_by_x.setFont(font)
        self.button_divide_by_x.setObjectName("button_divide_by_x")
        self.gridLayout.addWidget(self.button_divide_by_x, 5, 2, 1, 1)
        self.button_divide = QtWidgets.QPushButton(self.centralwidget)
        self.button_divide.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_divide.sizePolicy().hasHeightForWidth())
        self.button_divide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_divide.setFont(font)
        self.button_divide.setObjectName("button_divide")
        self.gridLayout.addWidget(self.button_divide, 5, 5, 1, 1)
        self.button_del = QtWidgets.QPushButton(self.centralwidget)
        self.button_del.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_del.sizePolicy().hasHeightForWidth())
        self.button_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_del.setFont(font)
        self.button_del.setObjectName("button_del")
        self.gridLayout.addWidget(self.button_del, 2, 5, 1, 1)
        self.button_pow = QtWidgets.QPushButton(self.centralwidget)
        self.button_pow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pow.sizePolicy().hasHeightForWidth())
        self.button_pow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_pow.setFont(font)
        self.button_pow.setObjectName("button_pow")
        self.gridLayout.addWidget(self.button_pow, 4, 4, 1, 1)
        self.button_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.button_sqrt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sqrt.sizePolicy().hasHeightForWidth())
        self.button_sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setObjectName("button_sqrt")
        self.gridLayout.addWidget(self.button_sqrt, 5, 3, 1, 1)
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_plus.sizePolicy().hasHeightForWidth())
        self.button_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_plus.setFont(font)
        self.button_plus.setObjectName("button_plus")
        self.gridLayout.addWidget(self.button_plus, 8, 5, 1, 1)
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minus.sizePolicy().hasHeightForWidth())
        self.button_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        self.gridLayout.addWidget(self.button_minus, 7, 5, 1, 1)
        self.button_zero = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_zero.sizePolicy().hasHeightForWidth())
        self.button_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_zero.setFont(font)
        self.button_zero.setObjectName("button_zero")
        self.gridLayout.addWidget(self.button_zero, 9, 2, 1, 2)
        self.button_log = QtWidgets.QPushButton(self.centralwidget)
        self.button_log.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_log.sizePolicy().hasHeightForWidth())
        self.button_log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_log.setFont(font)
        self.button_log.setObjectName("button_log")
        self.gridLayout.addWidget(self.button_log, 4, 0, 1, 1)
        self.button_ln = QtWidgets.QPushButton(self.centralwidget)
        self.button_ln.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ln.sizePolicy().hasHeightForWidth())
        self.button_ln.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ln.setFont(font)
        self.button_ln.setObjectName("button_ln")
        self.gridLayout.addWidget(self.button_ln, 4, 2, 1, 1)
        self.button_sin = QtWidgets.QPushButton(self.centralwidget)
        self.button_sin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sin.sizePolicy().hasHeightForWidth())
        self.button_sin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_sin.setFont(font)
        self.button_sin.setObjectName("button_sin")
        self.gridLayout.addWidget(self.button_sin, 6, 0, 1, 1)
        self.button_cos = QtWidgets.QPushButton(self.centralwidget)
        self.button_cos.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cos.sizePolicy().hasHeightForWidth())
        self.button_cos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_cos.setFont(font)
        self.button_cos.setObjectName("button_cos")
        self.gridLayout.addWidget(self.button_cos, 7, 0, 1, 1)
        self.button_tan = QtWidgets.QPushButton(self.centralwidget)
        self.button_tan.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_tan.sizePolicy().hasHeightForWidth())
        self.button_tan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_tan.setFont(font)
        self.button_tan.setObjectName("button_tan")
        self.gridLayout.addWidget(self.button_tan, 8, 0, 1, 1)
        self.button_cot = QtWidgets.QPushButton(self.centralwidget)
        self.button_cot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cot.sizePolicy().hasHeightForWidth())
        self.button_cot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_cot.setFont(font)
        self.button_cot.setObjectName("button_cot")
        self.gridLayout.addWidget(self.button_cot, 9, 0, 1, 1)
        self.button_factorial = QtWidgets.QPushButton(self.centralwidget)
        self.button_factorial.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_factorial.sizePolicy().hasHeightForWidth())
        self.button_factorial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_factorial.setFont(font)
        self.button_factorial.setDefault(False)
        self.button_factorial.setFlat(False)
        self.button_factorial.setObjectName("button_factorial")
        self.gridLayout.addWidget(self.button_factorial, 5, 0, 1, 1)
        self.button_random = QtWidgets.QPushButton(self.centralwidget)
        self.button_random.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_random.sizePolicy().hasHeightForWidth())
        self.button_random.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_random.setFont(font)
        self.button_random.setObjectName("button_random")
        self.gridLayout.addWidget(self.button_random, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 0, 1, 2)
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)
        Calculator.setTabOrder(self.button_two, self.button_three)
        Calculator.setTabOrder(self.button_three, self.button_five)
        Calculator.setTabOrder(self.button_five, self.button_six)
        Calculator.setTabOrder(self.button_six, self.button_eight)
        Calculator.setTabOrder(self.button_eight, self.button_nine)
        Calculator.setTabOrder(self.button_nine, self.button_zero)
        Calculator.setTabOrder(self.button_zero, self.button_decimal)
        Calculator.setTabOrder(self.button_decimal, self.button_divide)
        Calculator.setTabOrder(self.button_divide, self.button_multiply)
        Calculator.setTabOrder(self.button_multiply, self.button_minus)
        Calculator.setTabOrder(self.button_minus, self.button_plus)
        Calculator.setTabOrder(self.button_plus, self.button_equals)
        Calculator.setTabOrder(self.button_equals, self.button_change)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "CalcChamp"))
        Calculator.setProperty("class", _translate("Calculator", "darkButton"))
        self.button_change.setText(_translate("Calculator", "☰"))
        self.button_change.setProperty("class", _translate("Calculator", "hamburger"))
        self.label_style.setText(_translate("Calculator", "Scientific"))
        self.line_result.setText(_translate("Calculator", "0"))
        self.button_equals.setText(_translate("Calculator", "="))
        self.button_equals.setProperty("class", _translate("Calculator", "resultbutton"))
        self.button_five.setText(_translate("Calculator", "5"))
        self.button_five.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_eight.setText(_translate("Calculator", "8"))
        self.button_eight.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_multiply.setText(_translate("Calculator", "*"))
        self.button_multiply.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_two.setText(_translate("Calculator", "2"))
        self.button_two.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_root.setText(_translate("Calculator", "ⁿ√x"))
        self.button_root.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_decimal.setText(_translate("Calculator", ","))
        self.button_decimal.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_c.setText(_translate("Calculator", "C"))
        self.button_c.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_ce.setText(_translate("Calculator", "CE"))
        self.button_ce.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_nine.setText(_translate("Calculator", "9"))
        self.button_nine.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_three.setText(_translate("Calculator", "3"))
        self.button_three.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_sqr.setText(_translate("Calculator", "x²"))
        self.button_sqr.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_six.setText(_translate("Calculator", "6"))
        self.button_six.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_negation.setText(_translate("Calculator", "+-"))
        self.button_negation.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_one.setText(_translate("Calculator", "1"))
        self.button_one.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_exp.setText(_translate("Calculator", "eˣ"))
        self.button_exp.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_four.setText(_translate("Calculator", "4"))
        self.button_four.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_seven.setText(_translate("Calculator", "7"))
        self.button_seven.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_divide_by_x.setText(_translate("Calculator", "⅟ₓ"))
        self.button_divide_by_x.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_divide.setText(_translate("Calculator", "/"))
        self.button_divide.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_del.setText(_translate("Calculator", "DEL"))
        self.button_del.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_pow.setText(_translate("Calculator", "xⁿ"))
        self.button_pow.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_sqrt.setText(_translate("Calculator", "√x"))
        self.button_sqrt.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_plus.setText(_translate("Calculator", "+"))
        self.button_plus.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_minus.setText(_translate("Calculator", "-"))
        self.button_minus.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_zero.setText(_translate("Calculator", "0"))
        self.button_zero.setProperty("class", _translate("Calculator", "lightbutton"))
        self.button_log.setText(_translate("Calculator", "log"))
        self.button_log.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_ln.setText(_translate("Calculator", "ln"))
        self.button_ln.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_sin.setText(_translate("Calculator", "sin"))
        self.button_sin.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_cos.setText(_translate("Calculator", "cos"))
        self.button_cos.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_tan.setText(_translate("Calculator", "tan"))
        self.button_tan.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_cot.setText(_translate("Calculator", "cot"))
        self.button_cot.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_factorial.setText(_translate("Calculator", "x!"))
        self.button_factorial.setProperty("class", _translate("Calculator", "darkbutton"))
        self.button_random.setText(_translate("Calculator", "🎲"))
        self.button_random.setProperty("class", _translate("Calculator", "darkbutton"))
